#Use root/example as user/password credentials
version: '3.1'

services:
  
  mongo_db:
    image: mongo
    restart: always
  mongo_seed:
    build: ./mongo-seed
    links:
      - mongo_db
  server:
    image: nodejs
    volumes:
      - .:/server
      - /server/node_modules
    build: .
    restart: always
    ports:
      - 8000:8000
    environment:
      - MONGODB_URL=mongodb+srv://bilgerjeremy5705:b8209ze6531@cluster0.icxtwoq.mongodb.net/IntegDeploy?retryWrites=true&w=majority&appName=Cluster0
      - PORT=8000
      - FRONT_URL
    depends_on:
      - mongo_db
    command: sh -c "npm install && node server.js"