name: Vercel Production Deployment

env: 
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build_test_and_deploy:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build the stack with docker
        run: docker compose -f docker-compose.yml up -d

      - name: npm ci and test
        run: |
          sudo npm ci
          sudo npm run cypress:run

      - name: Stop the stack
        run: docker compose -f docker-compose.yml down

      - name: Install Vercel CLI
        run: sudo npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: sudo vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: sudo vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: sudo vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

  trigger-event:
    runs-on: ubuntu-latest
    needs: build_test_and_deploy
    steps:
      - name: Fire event
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PERSONNAL_ACCESS_TOKEN }}" \
          -H "X-Github-Api-Version: 2022-11-28" \
          https://api.github.com/repos/VioletThe25th/react-integdeploy/dispatches \
          -d '{"event_type":"dispatch-event"}'