name: Vercel Production Deployment

env: 
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  build_test_and_deploy:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # Récupération du code source
      - uses: actions/checkout@v4
      
      # Installation de Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with: 
          node-version: ${{ matrix.node-version }}

      # Installation des dépendances et exécution des tests
      - name: npm ci and test
        run: |
          npm ci
          npm test

      # Installation de la CLI Vercel
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      # Récupération des variables d'environnement de Vercel
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      # Construction des artefacts du projet
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      # Déploiement sur Vercel
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
